[tool.poetry]
name = "gtr-pi-car"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
motor = "^3.5.1"
pymongo = "^4.8.0"
python-dotenv = "^1.0.0"
uvicorn = {extras = ["standard"], version = "^0.30.0"}
opencv-python-headless = "^4.10.0.84"
ultralytics = "^8.4.41"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"